//Colors
export const colors = [
  '#32a852',
  '#8ba832',
  '#a88b32',
  '#a86332',
  '#a83632',
  '#32a8a6',
  '#327da8',
  '#3246a8',
  '#6b32a8'
];

//Names
export const names = [
  'Main Street',
  'Church Street',
  'Main Street North',
  'Main Street South',
  'High Street',
  'Elm Street',
  'Main Street West',
  'Washington Street',
  'Park Avenue',
  'Main Street East',
  'Walnut Street',
  '2nd Street',
  'Chestnut Street',
  'Maple Avenue',
  'Maple Street',
  'Broad Street',
  'Oak Street',
  'Center Street',
  'River Road',
  'Pine Street',
  'Water Street',
  'Market Street',
  'South Street',
  'Union Street',
  'Park Street',
  '3rd Street',
  'Washington Avenue',
  'Cherry Street',
  'Highland Avenue',
  'Court Street',
  'North Street',
  'Mill Street',
  '4th Street',
  'Spring Street',
  'School Street',
  'Prospect Street',
  'Franklin Street',
  'Central Avenue',
  '1st Street',
  'State Street',
  'West Street',
  'Front Street',
  'Jefferson Street',
  'Cedar Street',
  'Park Place',
  'Locust Street',
  'Bridge Street',
  'Madison Avenue',
  'Jackson Street',
  'Spruce Street',
  'Ridge Road',
  'Meadow Lane',
  'Grove Street',
  '5th Street',
  'Pearl Street',
  'Lincoln Street',
  'Pleasant Street',
  'Pennsylvania Avenue',
  'Dogwood Drive',
  'Madison Street',
  'Lincoln Avenue',
  'Jefferson Avenue',
  'Adams Street',
  'Academy Street',
  '7th Street',
  '4th Street West',
  'Route 1',
  'Green Street',
  'East Street',
  '3rd Street West',
  '11th Street',
  'Summit Avenue',
  'River Street',
  'Elizabeth Street',
  'Cherry Lane'
];
